<template>
  <div>
    <shopHeader :topData='foods.rst'/>
    <!-- <div class='shoptab'>
      <router-link :to='{ name: 'goods' }' active-class='select' class='shoptabItem'><span>点餐</span></router-link>
      <router-link :to='{ name: 'ratings' }' active-class='select' class='shoptabItem'><span>评价</span></router-link>
      <router-link :to='{ name: 'seller' }' active-class='select' class='shoptabItem'><span>商家</span></router-link>
    </div>
    <router-view :foods='foods'/> -->
    <div class='shoptab' ref="shoptab">
      <div class='shoptabItem' :class="isShow === 0 ? 'select' : ''" @click='handleShopTabItem(0)'><span>点餐</span></div>
      <div class='shoptabItem' :class="isShow === 1 ? 'select' : ''" @click='handleShopTabItem(1)'><span>评价</span></div>
      <div class='shoptabItem' :class="isShow === 2 ? 'select' : ''" @click='handleShopTabItem(2)'><span>商家</span></div>
    </div>
<<<<<<< HEAD
    <c-goods v-if='isShow === 0' :foods='foods'/>
    <c-ratings v-if='isShow === 1'/>
    <c-seller v-if='isShow === 2' :seller='foods.rst'/>
=======
    <!-- 点餐 -->
    <c-goods v-if="isShow === 0" :foods="foods"/>
    <!-- 评价 -->
    <c-ratings v-if="isShow === 1"/>
    <!-- 商家 -->
    <c-seller v-if="isShow === 2" :seller="foods.rst"/>
>>>>>>> fdea70c7435298e9ca110db22d250de0d71c20df
  </div>
</template>

<script>
import shopHeader from './shopHeader'
import cGoods from '../goods/goods'
import cRatings from '../ratings/ratings'
import cSeller from '../seller/seller'
export default {
  name: 'shop',
  components: {
    shopHeader,
    cGoods,
    cRatings,
    cSeller
  },
  data() {
    return {
      isShow: 0, // 判断 点餐，评价，商家是否加载
      foods: {
        bought_list: {
          food_ids: [],
          grey_icon_url: 'b571e9375597c7dd8e5b7bd32120928epng',
          icon_url: 'db75a248a885c94c389b5bbc5c8d876apng',
          text: '买过'
        },
        menu: [
          {
            activity: null,
            description: '大家喜欢吃，才叫真好吃。',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68',icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）,180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'a4a31d4456a8c7323c79641cb6389278jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658674372',
                limitation: {},
                min_purchase: 1,
                month_sales: 176,
                name: '肥西老母鸡汤小份',
                photos: ['a4a31d4456a8c7323c79641cb6389278jpeg'],
                rating: 4.07,
                rating_count: 29,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 29,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225321,
                  is_essential: false,
                  item_id: '455658674372',
                  name: '肥西老母鸡汤小份',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangxiaofen',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 176,
                  recent_rating: 4.07,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190739652',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516637,
                  weight: 0
                }],
                specifications: [],
                tips: '29评价 月售176份',
                type: null,
                video: null,
                virtual_food_id: 848516637
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：酱香（主要原料：鸡蛋、青葱、咸鸡油、清酱汁、蚕豆酱）颜色分明，味道香醇、原汁原味，老乡鸡蒸好的蛋，吃起来紧实，有浓浓的蛋香',
                image_path: '36d52796494b689aaca2654086f8f21bjpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455654499524',
                limitation: {},
                min_purchase: 1,
                month_sales: 175,
                name: '农家蒸蛋',
                photos: ['36d52796494b689aaca2654086f8f21bjpeg'],
                rating: 4.16,
                rating_count: 57,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 56,
                satisfy_rate: 98,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900221995,
                  is_essential: false,
                  item_id: '455654499524',
                  name: '农家蒸蛋',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'nongjiazhengdan',
                  price: 8,
                  promotion_stock: -1,
                  recent_popularity: 175,
                  recent_rating: 4.16,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522187307204',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848512538,
                  weight: 0
                }],
                specifications: [],
                tips: '57评价 月售175份',
                type: null,
                video: null,
                virtual_food_id: 848512538
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 547048976,
                cold_box: null,
                coupons: null,
                description: '1份/口味：葱香（主要原料：菜苔、红葱酥油）精选标准的菜苔，经焯水后，佐以葱油调味，成品葱香浓郁，菜苔爽口',
                image_path: '810fc144f1def01fe6ecaa48d9906432jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000031703642308',
                limitation: {},
                min_purchase: 1,
                month_sales: 133,
                name: '葱油菜苔',
                photos: ['810fc144f1def01fe6ecaa48d9906432jpeg'],
                rating: 4.31,
                rating_count: 39,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 39,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [
                  {
                    checkout_mode: 1,
                    coupon_id: -1,
                    food_id: 1712518031,
                    is_essential: false,
                    item_id: '100000031703642308',
                    name: '葱油菜苔',
                    original_price: null,
                    packing_fee: 0.5,
                    partial_reduce_activity_id: null,
                    pid: null,
                    pinyin_name: 'congyoucaitai',
                    price: 8,
                    promotion_stock: -1,
                    recent_popularity: 133,
                    recent_rating: 4.31,
                    restaurant_id: 'E2250635489379941286',
                    sku_id: '100000040196571332',
                    sold_out: false,
                    specs: [],
                    stock: 9999,
                    virtual_food_id: 1704271152,
                    weight: 0
                  }
                ],
                specifications: [],
                tips: '39评价 月售133份',
                type: null,
                video: null,
                virtual_food_id: 1704271152
              },
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：香辣（主要原料：青鱼块、鲜红椒、清酱汁）青鱼与鸡汤的相逢，注定会在味蕾呈现出精彩绝伦的滋味，与寡淡相对而言，我们更会营造“精彩”二字',
                image_path: 'b6a4e11a76c93d7183dc770e29770beajpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455640114372',
                limitation: {},
                min_purchase: 1,
                month_sales: 76,
                name: '鸡汁辣鱼',
                photos: ['b6a4e11a76c93d7183dc770e29770beajpeg'],
                rating: 4.32,
                rating_count: 19,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 19,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900230326,
                  is_essential: false,
                  item_id: '455640114372',
                  name: '鸡汁辣鱼',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'jizhilayu',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 76,
                  recent_rating: 4.32,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522195825860',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848498468,
                  weight: 0
                }],
                specifications: [],
                tips: '19评价 月售76份',
                type: null,
                video: null,
                virtual_food_id: 848498468
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：猪肉香肠、豆米、咸鸡油）↵另类的“江南腌笃鲜”，米饭的好搭档，老乡鸡既保留了时令菜的滋味，更创新了时令菜的口感',
                image_path: '3c924f771706153156032bfc0358fabbjpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455645129924',
                limitation: {},
                min_purchase: 1,
                month_sales: 75,
                name: '香肠蒸豆米',
                photos: ['3c924f771706153156032bfc0358fabbjpeg'],
                rating: 4.22,
                rating_count: 18,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 18,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225307,
                  is_essential: false,
                  item_id: '455645129924',
                  name: '香肠蒸豆米',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xiangchangzhengdoumi',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 75,
                  recent_rating: 4.22,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190725316',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848503352,
                  weight: 0
                }],
                specifications: [],
                tips: '18评价 月售75份',
                type: null,
                video: null,
                virtual_food_id: 848503352
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：葱香（主要原料：鸡块、葱油、青葱、姜片、极鲜酱油）经典的台柱子，180天的农家散养土鸡，历经葱油的洗礼后，鸡肉滑润细嫩，清鲜醇厚，葱香四溢',
                image_path: 'f53dfdde30da09800f6a5798c5f486b6jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649787076',
                limitation: {},
                min_purchase: 1,
                month_sales: 74,
                name: '葱油鸡',
                photos: ['f53dfdde30da09800f6a5798c5f486b6jpeg'],
                rating: 4.09,
                rating_count: 11,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 10,
                satisfy_rate: 90,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239377,
                  is_essential: false,
                  item_id: '455649787076',
                  name: '葱油鸡',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'congyouji',
                  price: 17,
                  promotion_stock: -1,
                  recent_popularity: 74,
                  recent_rating: 4.09,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205128900',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848507928,
                  weight: 0
                }],
                specifications: [],
                tips: '11评价 月售74份',
                type: null,
                video: null,
                virtual_food_id: 848507928
              },
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547029122,
                cold_box: null,
                coupons: null,
                description: '1份/口味：剁椒（主要原料：青鱼头、泡椒）“蒸”菜的代表，新鲜的鱼头浸润在爽口的泡椒中，刺激感爆棚',
                image_path: '544fc2df4aa12b9ed698996910864cedjpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455649765572',
                limitation: {},
                min_purchase: 1,
                month_sales: 57,
                name: '剁椒鱼头',
                photos: ['544fc2df4aa12b9ed698996910864cedjpeg'],
                rating: 4.11,
                rating_count: 9,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 9,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239354,
                  is_essential: false,
                  item_id: '455649765572',
                  name: '剁椒鱼头',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'duojiaoyutou',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 57,
                  recent_rating: 4.11,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205105348',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507907,
                  weight: 0
                }],
                specifications: [],
                tips: '9评价 月售57份',
                type: null,
                video: null,
                virtual_food_id: 848507907
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 547029122,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：五花肉、米粉）老乡鸡的粉蒸肉独有特色，滋润软糯，味美香咸',
                image_path: 'd278e62a7d67fe50b80253a0b432d8d3jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '512777575620',
                limitation: {},
                min_purchase: 1,
                month_sales: 43,
                name: '粉蒸肉',
                photos: ['d278e62a7d67fe50b80253a0b432d8d3jpeg'],
                rating: 4.43,
                rating_count: 7,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 7,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 963070745,
                  is_essential: false,
                  item_id: '512777575620',
                  name: '粉蒸肉',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'fenzhengrou',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 43,
                  recent_rating: 4.43,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '586558933188',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 904286918,
                  weight: 0
                }],
                specifications: [],
                tips: '7评价 月售43份',
                type: null,
                video: null,
                virtual_food_id: 904286918
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547048976,
                cold_box: null,
                coupons: null,
                description: '1份/口味：甜味（主要原料：南瓜、蜂蜜、白糖）蜜汁南瓜作为当地的一道特色小吃，口感绵软，香甜怡人，深受广大顾客所喜爱',
                image_path: '72834276d6807688461310655011f754jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455640096964',
                limitation: {},
                min_purchase: 1,
                month_sales: 24,
                name: '蜜汁南瓜',
                photos: ['72834276d6807688461310655011f754jpeg'],
                rating: 4.14,
                rating_count: 7,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 7,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900230309,
                  is_essential: false,
                  item_id: '455640096964',
                  name: '蜜汁南瓜',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'mizhinangua',
                  price: 9,
                  promotion_stock: -1,
                  recent_popularity: 24,
                  recent_rating: 4.14,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522195808452',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848498451,
                  weight: 0
                }],
                specifications: [],
                tips: '7评价 月售24份',
                type: null,
                video: null,
                virtual_food_id: 848498451
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：五花肉、梅干菜、蚝油、老抽）厚重香浓的五花肉将梅干菜绵密寡淡的滋味驯化，上等的耗油淋漓出软糯滋润的回味感，各有主次却又相互填补。这份梅菜扣肉蕴藏着一个杂食主义者对荤素融合恰到好处的服帖感',
                image_path: '25c53591119ba53456e665d30f10b6cbjpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649790148',
                limitation: {},
                min_purchase: 1,
                month_sales: 56,
                name: '梅菜扣肉',
                photos: ['25c53591119ba53456e665d30f10b6cbjpeg'],
                rating: 4,
                rating_count: 3,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 3,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239380,
                  is_essential: false,
                  item_id: '455649790148',
                  name: '梅菜扣肉',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'meicaikourou',
                  price: 16,
                  promotion_stock: -1,
                  recent_popularity: 56,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205131972',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507931,
                  weight: 0
                }],
                specifications: [],
                tips: '3评价 月售56份',
                type: null,
                video: null,
                virtual_food_id: 848507931
              }
            ],
            global_id: '-1',
            grey_icon_url: 'aba732b4ca103b2521c872442d7e5d4epng',
            icon_url: '06a05b267f338acfeb8bd682d16e836dpng',
            id: -1,
            is_activity: null,
            is_selected: true,
            name: '热销',
            type: 2
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'a4a31d4456a8c7323c79641cb6389278jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658674372',
                limitation: {},
                min_purchase: 1,
                month_sales: 176,
                name: '肥西老母鸡汤小份',
                photos: ['a4a31d4456a8c7323c79641cb6389278jpeg'],
                rating: 4.07,
                rating_count: 29,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 29,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225321,
                  is_essential: false,
                  item_id: '455658674372',
                  name: '肥西老母鸡汤小份',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangxiaofen',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 176,
                  recent_rating: 4.07,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190739652',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516637,
                  weight: 0
                }],
                specifications: [],
                tips: '29评价 月售176份',
                type: null,
                video: null,
                virtual_food_id: 848516637
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'dd3ea4f36c7925753c6aa049c17cc36djpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658675396',
                limitation: {},
                min_purchase: 1,
                month_sales: 16,
                name: '肥西老母鸡汤中份',
                photos: ['dd3ea4f36c7925753c6aa049c17cc36djpeg'],
                rating: 4.33,
                rating_count: 3,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 3,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225322,
                  is_essential: false,
                  item_id: '455658675396',
                  name: '肥西老母鸡汤中份',
                  original_price: null,
                  packing_fee: 1,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangzhongfen',
                  price: 36,
                  promotion_stock: -1,
                  recent_popularity: 16,
                  recent_rating: 4.33,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190740676',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516638,
                  weight: 0
                }],
                specifications: [],
                tips: '3评价 月售16份',
                type: null,
                video: null,
                virtual_food_id: 848516638
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'dd3ea4f36c7925753c6aa049c17cc36djpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649806532',
                limitation: {},
                min_purchase: 1,
                month_sales: 1,
                name: '肥西老母鸡汤大份',
                photos: ['dd3ea4f36c7925753c6aa049c17cc36djpeg'],
                rating: 2,
                rating_count: 1,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 0,
                satisfy_rate: 0,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239401,
                  is_essential: false,
                  item_id: '455649806532',
                  name: '肥西老母鸡汤大份',
                  original_price: null,
                  packing_fee: 2,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangdafen',
                  price: 66,
                  promotion_stock: -1,
                  recent_popularity: 1,
                  recent_rating: 2,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205153476',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507947,
                  weight: 0
                }],
                specifications: [],
                tips: '1评价 月售1份',
                type: null,
                video: null,
                virtual_food_id: 848507947
              }
            ],
            global_id: '46768370884',
            grey_icon_url: '',
            icon_url: '',
            id: 533299675,
            is_activity: false,
            is_selected: false,
            name: '招牌鸡汤',
            type: 1
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 1678274160,
                cold_box: null,
                coupons: null,
                description: '1份/口味：酱香微辣（主要原料：排骨、年糕）排骨浓香，年糕软糯酥脆，整道菜口感鲜嫩适口，略有甜辣味',
                image_path: 'cfe136bf31d6f876d3fd1426582f36c2jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000042562062532',
                limitation: {},
                min_purchase: 1,
                month_sales: 14,
                name: '排骨年糕',
                photos: ['cfe136bf31d6f876d3fd1426582f36c2jpeg'],
                rating: 0,
                rating_count: 0,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 0,
                satisfy_rate: 0,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 1725616089,
                  is_essential: false,
                  item_id: '100000042562062532',
                  name: '排骨年糕',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'paiguniangao',
                  price: 18,
                  promotion_stock: -1,
                  recent_popularity: 14,
                  recent_rating: 0,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '100000053565542596',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 1714809055,
                  weight: 0
                }],
                specifications: [],
                tips: '0评价 月售14份',
                type: null,
                video: null,
                virtual_food_id: 1714809055
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 1678274160,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜微辣（主要原料：雪菜、笋尖干）高山鲜笋，腌菜坛香，一口香脆，下饭滋味',
                image_path: '25dae78f148ea591c52d8dd9a6603d07jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000042616406212',
                limitation: {},
                min_purchase: 1,
                month_sales: 20,
                name: '雪菜山笋',
                photos: ['25dae78f148ea591c52d8dd9a6603d07jpeg'],
                rating: 4,
                rating_count: 2,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 2,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 1725589876,
                  is_essential: false,
                  item_id: '100000042616406212',
                  name: '雪菜山笋',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xuecaishansun',
                  price: 13,
                  promotion_stock: -1,
                  recent_popularity: 20,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '100000053609031876',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 1714851351,
                  weight: 0
                }],
                specifications: [],
                tips: '2评价 月售20份',
                type: null,
                video: null,
                virtual_food_id: 1714851351
              }
            ],
            global_id: '100000005054984388',
            grey_icon_url: '',
            icon_url: '',
            id: 1678274160,
            is_activity: false,
            is_selected: false,
            name: '新上菜品',
            type: 1
          },
          {
            activity: null,
            description: '米饭需要单点，本店所售菜品均不包含米饭。',
            foods: [{
              activity: null,
              attributes: [],
              attrs: [],
              brand: null,
              category_id: 533304346,
              cold_box: null,
              coupons: null,
              description: '【强调】本店所有菜品均不含米饭，米饭需单点1份/口味：原味（主要原料：大米、大豆油）老乡鸡精选黑龙江省响水大米，颗粒丰满，质地坚硬，色泽青白、透明纯净，焖出的饭，汤似鲜乳，米如油注，饭质柔软，香味袭人。具有软糯、微甜、芳香的特征，彰显出米饭的原色原香',
              image_path: '94eefa4bcb0596c1e7284fe96d276740jpeg',
              is_essential: false,
              is_featured: 0,
              item_id: '455635042500',
              limitation: {},
              min_purchase: 1,
              month_sales: 766,
              name: '米饭',
              photos: ['94eefa4bcb0596c1e7284fe96d276740jpeg'],
              rating: 4.24,
              rating_count: 131,
              restaurant_id: 'E2250635489379941286',
              satisfy_count: 130,
              satisfy_rate: 99,
              scheme: null,
              specfoods: [{
                checkout_mode: 1,
                coupon_id: -1,
                food_id: 900212088,
                is_essential: false,
                item_id: '455635042500',
                name: '米饭',
                original_price: null,
                packing_fee: 0.5,
                partial_reduce_activity_id: null,
                pid: null,
                pinyin_name: 'mifan',
                price: 2,
                promotion_stock: -1,
                recent_popularity: 766,
                recent_rating: 4.24,
                restaurant_id: 'E2250635489379941286',
                sku_id: '522177177796',
                sold_out: false,
                specs: [],
                stock: 9995,
                virtual_food_id: 848493533,
                weight: 0
              }],
              specifications: [],
              tips: '131评价 月售766份',
              type: null,
              video: null,
              virtual_food_id: 848493533
            }],
            global_id: '46773153988',
            grey_icon_url: '',
            icon_url: '',
            id: 533304346,
            is_activity: false,
            is_selected: false,
            name: '主食【需单点】',
            type: 1
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547058978,
                cold_box: null,
                coupons: null,
                description: '1份/口味：香辣（主要原料：萝卜丝、香菜、红椒丝、榨菜丝）菜品口感鲜嫩爽脆，口味清香可口',
                image_path: 'b71643f0f99c657c6fe110af29915b33jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455620789444',
                limitation: {},
                min_purchase: 1,
                month_sales: 24,
                name: '菜根香',
                photos: ['b71643f0f99c657c6fe110af29915b33jpeg'],
                rating: 3.8,
                rating_count: 5,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 4,
                satisfy_rate: 80,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900216214,
                  is_essential: false,
                  item_id: '455620789444',
                  name: '菜根香',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'caigenxiang',
                  price: 3,
                  promotion_stock: -1,
                  recent_popularity: 24,
                  recent_rating: 3.8,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522181397700',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848479595,
                  weight: 0
                }],
                specifications: [],
                tips: '5评价 月售24份',
                type: null,
                video: null,
                virtual_food_id: 848479595
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547058978,
                cold_box: null,
                coupons: null,
                description: '1个/口味：咸味（主要原料：鸭蛋、精盐）蛋白柔嫩，颜色细而油多，食后颇有“曾经沧海难为水，他乡咸鸭蛋，我实在瞧不上”的感慨',
                image_path: '2327c87cf1040e421d75c882ed6e34c2jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455630194884',
                limitation: {},
                min_purchase: 1,
                month_sales: 80,
                name: '咸鸭蛋',
                photos: ['2327c87cf1040e421d75c882ed6e34c2jpeg'],
                rating: 4,
                rating_count: 5,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 5,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900203726,
                  is_essential: false,
                  item_id: '455630194884',
                  name: '咸鸭蛋',
                  original_price: null,
                  packing_fee: 0,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xianyadan',
                  price: 3,
                  promotion_stock: -1,
                  recent_popularity: 80,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522168648900',
                  sold_out: false,
                  specs: [],
                  stock: 9985,
                  virtual_food_id: 848488826,
                  weight: 0
                }],
                specifications: [],
                tips: '5评价 月售80份',
                type: null,
                video: null,
                virtual_food_id: 848488826
              }
            ],
            global_id: '60888296644',
            grey_icon_url: '',
            icon_url: '',
            id: 547058978,
            is_activity: false,
            is_selected: false,
            name: '凑单神器',
            type: 1
          },
          {
            activity: null,
            description: '大家喜欢吃，才叫真好吃。',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68',icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）,180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'a4a31d4456a8c7323c79641cb6389278jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658674372',
                limitation: {},
                min_purchase: 1,
                month_sales: 176,
                name: '肥西老母鸡汤小份',
                photos: ['a4a31d4456a8c7323c79641cb6389278jpeg'],
                rating: 4.07,
                rating_count: 29,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 29,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225321,
                  is_essential: false,
                  item_id: '455658674372',
                  name: '肥西老母鸡汤小份',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangxiaofen',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 176,
                  recent_rating: 4.07,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190739652',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516637,
                  weight: 0
                }],
                specifications: [],
                tips: '29评价 月售176份',
                type: null,
                video: null,
                virtual_food_id: 848516637
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：酱香（主要原料：鸡蛋、青葱、咸鸡油、清酱汁、蚕豆酱）颜色分明，味道香醇、原汁原味，老乡鸡蒸好的蛋，吃起来紧实，有浓浓的蛋香',
                image_path: '36d52796494b689aaca2654086f8f21bjpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455654499524',
                limitation: {},
                min_purchase: 1,
                month_sales: 175,
                name: '农家蒸蛋',
                photos: ['36d52796494b689aaca2654086f8f21bjpeg'],
                rating: 4.16,
                rating_count: 57,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 56,
                satisfy_rate: 98,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900221995,
                  is_essential: false,
                  item_id: '455654499524',
                  name: '农家蒸蛋',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'nongjiazhengdan',
                  price: 8,
                  promotion_stock: -1,
                  recent_popularity: 175,
                  recent_rating: 4.16,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522187307204',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848512538,
                  weight: 0
                }],
                specifications: [],
                tips: '57评价 月售175份',
                type: null,
                video: null,
                virtual_food_id: 848512538
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 547048976,
                cold_box: null,
                coupons: null,
                description: '1份/口味：葱香（主要原料：菜苔、红葱酥油）精选标准的菜苔，经焯水后，佐以葱油调味，成品葱香浓郁，菜苔爽口',
                image_path: '810fc144f1def01fe6ecaa48d9906432jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000031703642308',
                limitation: {},
                min_purchase: 1,
                month_sales: 133,
                name: '葱油菜苔',
                photos: ['810fc144f1def01fe6ecaa48d9906432jpeg'],
                rating: 4.31,
                rating_count: 39,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 39,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [
                  {
                    checkout_mode: 1,
                    coupon_id: -1,
                    food_id: 1712518031,
                    is_essential: false,
                    item_id: '100000031703642308',
                    name: '葱油菜苔',
                    original_price: null,
                    packing_fee: 0.5,
                    partial_reduce_activity_id: null,
                    pid: null,
                    pinyin_name: 'congyoucaitai',
                    price: 8,
                    promotion_stock: -1,
                    recent_popularity: 133,
                    recent_rating: 4.31,
                    restaurant_id: 'E2250635489379941286',
                    sku_id: '100000040196571332',
                    sold_out: false,
                    specs: [],
                    stock: 9999,
                    virtual_food_id: 1704271152,
                    weight: 0
                  }
                ],
                specifications: [],
                tips: '39评价 月售133份',
                type: null,
                video: null,
                virtual_food_id: 1704271152
              },
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：香辣（主要原料：青鱼块、鲜红椒、清酱汁）青鱼与鸡汤的相逢，注定会在味蕾呈现出精彩绝伦的滋味，与寡淡相对而言，我们更会营造“精彩”二字',
                image_path: 'b6a4e11a76c93d7183dc770e29770beajpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455640114372',
                limitation: {},
                min_purchase: 1,
                month_sales: 76,
                name: '鸡汁辣鱼',
                photos: ['b6a4e11a76c93d7183dc770e29770beajpeg'],
                rating: 4.32,
                rating_count: 19,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 19,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900230326,
                  is_essential: false,
                  item_id: '455640114372',
                  name: '鸡汁辣鱼',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'jizhilayu',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 76,
                  recent_rating: 4.32,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522195825860',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848498468,
                  weight: 0
                }],
                specifications: [],
                tips: '19评价 月售76份',
                type: null,
                video: null,
                virtual_food_id: 848498468
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：猪肉香肠、豆米、咸鸡油）↵另类的“江南腌笃鲜”，米饭的好搭档，老乡鸡既保留了时令菜的滋味，更创新了时令菜的口感',
                image_path: '3c924f771706153156032bfc0358fabbjpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455645129924',
                limitation: {},
                min_purchase: 1,
                month_sales: 75,
                name: '香肠蒸豆米',
                photos: ['3c924f771706153156032bfc0358fabbjpeg'],
                rating: 4.22,
                rating_count: 18,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 18,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225307,
                  is_essential: false,
                  item_id: '455645129924',
                  name: '香肠蒸豆米',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xiangchangzhengdoumi',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 75,
                  recent_rating: 4.22,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190725316',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848503352,
                  weight: 0
                }],
                specifications: [],
                tips: '18评价 月售75份',
                type: null,
                video: null,
                virtual_food_id: 848503352
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：葱香（主要原料：鸡块、葱油、青葱、姜片、极鲜酱油）经典的台柱子，180天的农家散养土鸡，历经葱油的洗礼后，鸡肉滑润细嫩，清鲜醇厚，葱香四溢',
                image_path: 'f53dfdde30da09800f6a5798c5f486b6jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649787076',
                limitation: {},
                min_purchase: 1,
                month_sales: 74,
                name: '葱油鸡',
                photos: ['f53dfdde30da09800f6a5798c5f486b6jpeg'],
                rating: 4.09,
                rating_count: 11,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 10,
                satisfy_rate: 90,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239377,
                  is_essential: false,
                  item_id: '455649787076',
                  name: '葱油鸡',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'congyouji',
                  price: 17,
                  promotion_stock: -1,
                  recent_popularity: 74,
                  recent_rating: 4.09,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205128900',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848507928,
                  weight: 0
                }],
                specifications: [],
                tips: '11评价 月售74份',
                type: null,
                video: null,
                virtual_food_id: 848507928
              },
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547029122,
                cold_box: null,
                coupons: null,
                description: '1份/口味：剁椒（主要原料：青鱼头、泡椒）“蒸”菜的代表，新鲜的鱼头浸润在爽口的泡椒中，刺激感爆棚',
                image_path: '544fc2df4aa12b9ed698996910864cedjpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455649765572',
                limitation: {},
                min_purchase: 1,
                month_sales: 57,
                name: '剁椒鱼头',
                photos: ['544fc2df4aa12b9ed698996910864cedjpeg'],
                rating: 4.11,
                rating_count: 9,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 9,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239354,
                  is_essential: false,
                  item_id: '455649765572',
                  name: '剁椒鱼头',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'duojiaoyutou',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 57,
                  recent_rating: 4.11,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205105348',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507907,
                  weight: 0
                }],
                specifications: [],
                tips: '9评价 月售57份',
                type: null,
                video: null,
                virtual_food_id: 848507907
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 547029122,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：五花肉、米粉）老乡鸡的粉蒸肉独有特色，滋润软糯，味美香咸',
                image_path: 'd278e62a7d67fe50b80253a0b432d8d3jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '512777575620',
                limitation: {},
                min_purchase: 1,
                month_sales: 43,
                name: '粉蒸肉',
                photos: ['d278e62a7d67fe50b80253a0b432d8d3jpeg'],
                rating: 4.43,
                rating_count: 7,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 7,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 963070745,
                  is_essential: false,
                  item_id: '512777575620',
                  name: '粉蒸肉',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'fenzhengrou',
                  price: 14,
                  promotion_stock: -1,
                  recent_popularity: 43,
                  recent_rating: 4.43,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '586558933188',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 904286918,
                  weight: 0
                }],
                specifications: [],
                tips: '7评价 月售43份',
                type: null,
                video: null,
                virtual_food_id: 904286918
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547048976,
                cold_box: null,
                coupons: null,
                description: '1份/口味：甜味（主要原料：南瓜、蜂蜜、白糖）蜜汁南瓜作为当地的一道特色小吃，口感绵软，香甜怡人，深受广大顾客所喜爱',
                image_path: '72834276d6807688461310655011f754jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455640096964',
                limitation: {},
                min_purchase: 1,
                month_sales: 24,
                name: '蜜汁南瓜',
                photos: ['72834276d6807688461310655011f754jpeg'],
                rating: 4.14,
                rating_count: 7,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 7,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900230309,
                  is_essential: false,
                  item_id: '455640096964',
                  name: '蜜汁南瓜',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'mizhinangua',
                  price: 9,
                  promotion_stock: -1,
                  recent_popularity: 24,
                  recent_rating: 4.14,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522195808452',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848498451,
                  weight: 0
                }],
                specifications: [],
                tips: '7评价 月售24份',
                type: null,
                video: null,
                virtual_food_id: 848498451
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 547039020,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：五花肉、梅干菜、蚝油、老抽）厚重香浓的五花肉将梅干菜绵密寡淡的滋味驯化，上等的耗油淋漓出软糯滋润的回味感，各有主次却又相互填补。这份梅菜扣肉蕴藏着一个杂食主义者对荤素融合恰到好处的服帖感',
                image_path: '25c53591119ba53456e665d30f10b6cbjpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649790148',
                limitation: {},
                min_purchase: 1,
                month_sales: 56,
                name: '梅菜扣肉',
                photos: ['25c53591119ba53456e665d30f10b6cbjpeg'],
                rating: 4,
                rating_count: 3,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 3,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239380,
                  is_essential: false,
                  item_id: '455649790148',
                  name: '梅菜扣肉',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'meicaikourou',
                  price: 16,
                  promotion_stock: -1,
                  recent_popularity: 56,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205131972',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507931,
                  weight: 0
                }],
                specifications: [],
                tips: '3评价 月售56份',
                type: null,
                video: null,
                virtual_food_id: 848507931
              }
            ],
            global_id: '-1',
            grey_icon_url: 'aba732b4ca103b2521c872442d7e5d4epng',
            icon_url: '06a05b267f338acfeb8bd682d16e836dpng',
            id: -1,
            is_activity: null,
            is_selected: true,
            name: '热销',
            type: 2
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'a4a31d4456a8c7323c79641cb6389278jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658674372',
                limitation: {},
                min_purchase: 1,
                month_sales: 176,
                name: '肥西老母鸡汤小份',
                photos: ['a4a31d4456a8c7323c79641cb6389278jpeg'],
                rating: 4.07,
                rating_count: 29,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 29,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225321,
                  is_essential: false,
                  item_id: '455658674372',
                  name: '肥西老母鸡汤小份',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangxiaofen',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 176,
                  recent_rating: 4.07,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190739652',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516637,
                  weight: 0
                }],
                specifications: [],
                tips: '29评价 月售176份',
                type: null,
                video: null,
                virtual_food_id: 848516637
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'dd3ea4f36c7925753c6aa049c17cc36djpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658675396',
                limitation: {},
                min_purchase: 1,
                month_sales: 16,
                name: '肥西老母鸡汤中份',
                photos: ['dd3ea4f36c7925753c6aa049c17cc36djpeg'],
                rating: 4.33,
                rating_count: 3,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 3,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900225322,
                  is_essential: false,
                  item_id: '455658675396',
                  name: '肥西老母鸡汤中份',
                  original_price: null,
                  packing_fee: 1,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangzhongfen',
                  price: 36,
                  promotion_stock: -1,
                  recent_popularity: 16,
                  recent_rating: 4.33,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190740676',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516638,
                  weight: 0
                }],
                specifications: [],
                tips: '3评价 月售16份',
                type: null,
                video: null,
                virtual_food_id: 848516638
              },
              {
                activity: null,
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: null,
                category_id: 533299675,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'dd3ea4f36c7925753c6aa049c17cc36djpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649806532',
                limitation: {},
                min_purchase: 1,
                month_sales: 1,
                name: '肥西老母鸡汤大份',
                photos: ['dd3ea4f36c7925753c6aa049c17cc36djpeg'],
                rating: 2,
                rating_count: 1,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 0,
                satisfy_rate: 0,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900239401,
                  is_essential: false,
                  item_id: '455649806532',
                  name: '肥西老母鸡汤大份',
                  original_price: null,
                  packing_fee: 2,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'feixilaomujitangdafen',
                  price: 66,
                  promotion_stock: -1,
                  recent_popularity: 1,
                  recent_rating: 2,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205153476',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507947,
                  weight: 0
                }],
                specifications: [],
                tips: '1评价 月售1份',
                type: null,
                video: null,
                virtual_food_id: 848507947
              }
            ],
            global_id: '46768370884',
            grey_icon_url: '',
            icon_url: '',
            id: 533299675,
            is_activity: false,
            is_selected: false,
            name: '招牌鸡汤',
            type: 1
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 1678274160,
                cold_box: null,
                coupons: null,
                description: '1份/口味：酱香微辣（主要原料：排骨、年糕）排骨浓香，年糕软糯酥脆，整道菜口感鲜嫩适口，略有甜辣味',
                image_path: 'cfe136bf31d6f876d3fd1426582f36c2jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000042562062532',
                limitation: {},
                min_purchase: 1,
                month_sales: 14,
                name: '排骨年糕',
                photos: ['cfe136bf31d6f876d3fd1426582f36c2jpeg'],
                rating: 0,
                rating_count: 0,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 0,
                satisfy_rate: 0,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 1725616089,
                  is_essential: false,
                  item_id: '100000042562062532',
                  name: '排骨年糕',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'paiguniangao',
                  price: 18,
                  promotion_stock: -1,
                  recent_popularity: 14,
                  recent_rating: 0,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '100000053565542596',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 1714809055,
                  weight: 0
                }],
                specifications: [],
                tips: '0评价 月售14份',
                type: null,
                video: null,
                virtual_food_id: 1714809055
              },
              {
                activity: null,
                attributes: [{icon_color: '5ec452', icon_name: '新'}],
                attrs: [],
                brand: null,
                category_id: 1678274160,
                cold_box: null,
                coupons: null,
                description: '1份/口味：咸鲜微辣（主要原料：雪菜、笋尖干）高山鲜笋，腌菜坛香，一口香脆，下饭滋味',
                image_path: '25dae78f148ea591c52d8dd9a6603d07jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '100000042616406212',
                limitation: {},
                min_purchase: 1,
                month_sales: 20,
                name: '雪菜山笋',
                photos: ['25dae78f148ea591c52d8dd9a6603d07jpeg'],
                rating: 4,
                rating_count: 2,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 2,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 1725589876,
                  is_essential: false,
                  item_id: '100000042616406212',
                  name: '雪菜山笋',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xuecaishansun',
                  price: 13,
                  promotion_stock: -1,
                  recent_popularity: 20,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '100000053609031876',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 1714851351,
                  weight: 0
                }],
                specifications: [],
                tips: '2评价 月售20份',
                type: null,
                video: null,
                virtual_food_id: 1714851351
              }
            ],
            global_id: '100000005054984388',
            grey_icon_url: '',
            icon_url: '',
            id: 1678274160,
            is_activity: false,
            is_selected: false,
            name: '新上菜品',
            type: 1
          },
          {
            activity: null,
            description: '米饭需要单点，本店所售菜品均不包含米饭。',
            foods: [{
              activity: null,
              attributes: [],
              attrs: [],
              brand: null,
              category_id: 533304346,
              cold_box: null,
              coupons: null,
              description: '【强调】本店所有菜品均不含米饭，米饭需单点1份/口味：原味（主要原料：大米、大豆油）老乡鸡精选黑龙江省响水大米，颗粒丰满，质地坚硬，色泽青白、透明纯净，焖出的饭，汤似鲜乳，米如油注，饭质柔软，香味袭人。具有软糯、微甜、芳香的特征，彰显出米饭的原色原香',
              image_path: '94eefa4bcb0596c1e7284fe96d276740jpeg',
              is_essential: false,
              is_featured: 0,
              item_id: '455635042500',
              limitation: {},
              min_purchase: 1,
              month_sales: 766,
              name: '米饭',
              photos: ['94eefa4bcb0596c1e7284fe96d276740jpeg'],
              rating: 4.24,
              rating_count: 131,
              restaurant_id: 'E2250635489379941286',
              satisfy_count: 130,
              satisfy_rate: 99,
              scheme: null,
              specfoods: [{
                checkout_mode: 1,
                coupon_id: -1,
                food_id: 900212088,
                is_essential: false,
                item_id: '455635042500',
                name: '米饭',
                original_price: null,
                packing_fee: 0.5,
                partial_reduce_activity_id: null,
                pid: null,
                pinyin_name: 'mifan',
                price: 2,
                promotion_stock: -1,
                recent_popularity: 766,
                recent_rating: 4.24,
                restaurant_id: 'E2250635489379941286',
                sku_id: '522177177796',
                sold_out: false,
                specs: [],
                stock: 9995,
                virtual_food_id: 848493533,
                weight: 0
              }],
              specifications: [],
              tips: '131评价 月售766份',
              type: null,
              video: null,
              virtual_food_id: 848493533
            }],
            global_id: '46773153988',
            grey_icon_url: '',
            icon_url: '',
            id: 533304346,
            is_activity: false,
            is_selected: false,
            name: '主食【需单点】',
            type: 1
          },
          {
            activity: null,
            description: '',
            foods: [
              {
                activity: null,
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: null,
                category_id: 547058978,
                cold_box: null,
                coupons: null,
                description: '1份/口味：香辣（主要原料：萝卜丝、香菜、红椒丝、榨菜丝）菜品口感鲜嫩爽脆，口味清香可口',
                image_path: 'b71643f0f99c657c6fe110af29915b33jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455620789444',
                limitation: {},
                min_purchase: 1,
                month_sales: 24,
                name: '菜根香',
                photos: ['b71643f0f99c657c6fe110af29915b33jpeg'],
                rating: 3.8,
                rating_count: 5,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 4,
                satisfy_rate: 80,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900216214,
                  is_essential: false,
                  item_id: '455620789444',
                  name: '菜根香',
                  original_price: null,
                  packing_fee: 0.5,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'caigenxiang',
                  price: 3,
                  promotion_stock: -1,
                  recent_popularity: 24,
                  recent_rating: 3.8,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522181397700',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848479595,
                  weight: 0
                }],
                specifications: [],
                tips: '5评价 月售24份',
                type: null,
                video: null,
                virtual_food_id: 848479595
              },
              {
                activity: null,
                attributes: [],
                attrs: [],
                brand: null,
                category_id: 547058978,
                cold_box: null,
                coupons: null,
                description: '1个/口味：咸味（主要原料：鸭蛋、精盐）蛋白柔嫩，颜色细而油多，食后颇有“曾经沧海难为水，他乡咸鸭蛋，我实在瞧不上”的感慨',
                image_path: '2327c87cf1040e421d75c882ed6e34c2jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455630194884',
                limitation: {},
                min_purchase: 1,
                month_sales: 80,
                name: '咸鸭蛋',
                photos: ['2327c87cf1040e421d75c882ed6e34c2jpeg'],
                rating: 4,
                rating_count: 5,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 5,
                satisfy_rate: 100,
                scheme: null,
                specfoods: [{
                  checkout_mode: 1,
                  coupon_id: -1,
                  food_id: 900203726,
                  is_essential: false,
                  item_id: '455630194884',
                  name: '咸鸭蛋',
                  original_price: null,
                  packing_fee: 0,
                  partial_reduce_activity_id: null,
                  pid: null,
                  pinyin_name: 'xianyadan',
                  price: 3,
                  promotion_stock: -1,
                  recent_popularity: 80,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522168648900',
                  sold_out: false,
                  specs: [],
                  stock: 9985,
                  virtual_food_id: 848488826,
                  weight: 0
                }],
                specifications: [],
                tips: '5评价 月售80份',
                type: null,
                video: null,
                virtual_food_id: 848488826
              }
            ],
            global_id: '60888296644',
            grey_icon_url: '',
            icon_url: '',
            id: 547058978,
            is_activity: false,
            is_selected: false,
            name: '凑单神器',
            type: 1
          }
        ],
        recommend: [
          {
            items: [
              {
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: {attrs2: null, ingredient_info: null, show_photo_hash_type: 0, specifications2: null, sub_items: null},
                category_id: 46768370884,
                description: '1份/口味：咸鲜（主要原料：鸡块、农夫山泉纯净水、精盐）180天优质土鸡。精火熬炖，汤清肉白，原汁原味。中华烹饪协会评定为“中华名吃”',
                image_path: 'a4a31d4456a8c7323c79641cb6389278jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455658674372',
                min_purchase: 1,
                month_sales: 176,
                name: '肥西老母鸡汤小份',
                photos: ['a4a31d4456a8c7323c79641cb6389278jpeg'],
                rating: 4.07,
                rating_count: 29,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 29,
                satisfy_rate: 100,
                scheme: 'eleme://catering?target_food_id=900225321&restaurant_id=E2250635489379941286&category_id=46768370884',
                specfoods: [{
                  checkout_mode: 1,
                  food_id: 900225321,
                  is_essential: false,
                  item_id: '455658674372',
                  name: '肥西老母鸡汤小份',
                  packing_fee: 0.5,
                  pinyin_name: 'feixilaomujitangxiaofen',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 176,
                  recent_rating: 4.07,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522190739652',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848516637,
                  weight: 0
                }],
                specifications: [],
                tips: '29评价 月售176份',
                type: 0,
                virtual_food_id: 848516637
              },
              {
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: {attrs2: null, ingredient_info: null, show_photo_hash_type: 0, specifications2: null, sub_items: null},
                category_id: 60868151492,
                description: '1份/口味：葱香（主要原料：鸡块、葱油、青葱、姜片、极鲜酱油）经典的台柱子，180天的农家散养土鸡，历经葱油的洗礼后，鸡肉滑润细嫩，清鲜醇厚，葱香四溢',
                image_path: 'f53dfdde30da09800f6a5798c5f486b6jpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649787076',
                min_purchase: 1,
                month_sales: 74,
                name: '葱油鸡',
                photos: ['f53dfdde30da09800f6a5798c5f486b6jpeg'],
                rating: 4.09,
                rating_count: 11,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 10,
                satisfy_rate: 91,
                scheme: 'eleme://catering?target_food_id=900239377&restaurant_id=E2250635489379941286&category_id=60868151492',
                specfoods: [{
                  checkout_mode: 1,
                  food_id: 900239377,
                  is_essential: false,
                  item_id: '455649787076',
                  name: '葱油鸡',
                  packing_fee: 0.5,
                  pinyin_name: 'congyouji',
                  price: 17,
                  promotion_stock: -1,
                  recent_popularity: 74,
                  recent_rating: 4.09,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205128900',
                  sold_out: false,
                  specs: [],
                  stock: 9999,
                  virtual_food_id: 848507928,
                  weight: 0
                }],
                specifications: [],
                tips: '11评价 月售74份',
                type: 0,
                virtual_food_id: 848507928
              },
              {
                attributes: [{icon_color: 'ec9c68', icon_name: '招牌'}],
                attrs: [],
                brand: {attrs2: null, ingredient_info: null, show_photo_hash_type: 0, specifications2: null, sub_items: null},
                category_id: 60868151492,
                description: '1份/口味：咸鲜（主要原料：五花肉、梅干菜、蚝油、老抽）厚重香浓的五花肉将梅干菜绵密寡淡的滋味驯化，上等的耗油淋漓出软糯滋润的回味感，各有主次却又相互填补。这份梅菜扣肉蕴藏着一个杂食主义者对荤素融合恰到好处的服帖感',
                image_path: '25c53591119ba53456e665d30f10b6cbjpeg',
                is_essential: false,
                is_featured: 1,
                item_id: '455649790148',
                min_purchase: 1,
                month_sales: 56,
                name: '梅菜扣肉',
                photos: ['25c53591119ba53456e665d30f10b6cbjpeg'],
                rating: 4,
                rating_count: 3,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 3,
                satisfy_rate: 100,
                scheme: 'eleme://catering?target_food_id=900239380&restaurant_id=E2250635489379941286&category_id=60868151492',
                specfoods: [{
                  checkout_mode: 1,
                  food_id: 900239380,
                  is_essential: false,
                  item_id: '455649790148',
                  name: '梅菜扣肉',
                  packing_fee: 0.5,
                  pinyin_name: 'meicaikourou',
                  price: 16,
                  promotion_stock: -1,
                  recent_popularity: 56,
                  recent_rating: 4,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522205131972',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848507931,
                  weight: 0
                }],
                specifications: [],
                tips: '3评价 月售56份',
                type: 0,
                virtual_food_id: 848507931
              },
              {
                attributes: [{icon_color: 'ff5151', icon_name: '辣'}],
                attrs: [],
                brand: {attrs2: null, ingredient_info: null, show_photo_hash_type: 0, specifications2: null, sub_items: null},
                category_id: 60868151492,
                description: '1份/口味：香辣（主要原料：鸡胗、鸡心、鸡肺、鸡肝、红辣油、干辣椒、青葱、燕庄麻油）惹味儿！红油裹挟着的滋味，协同的精彩，只等你的发掘',
                image_path: '328a5417e927757ca0300d53ed0b0e74jpeg',
                is_essential: false,
                is_featured: 0,
                item_id: '455640115396',
                min_purchase: 1,
                month_sales: 33,
                name: '香辣鸡杂',
                photos: ['328a5417e927757ca0300d53ed0b0e74jpeg'],
                rating: 3.83,
                rating_count: 6,
                restaurant_id: 'E2250635489379941286',
                satisfy_count: 5,
                satisfy_rate: 83,
                scheme: 'eleme://catering?target_food_id=900230327&restaurant_id=E2250635489379941286&category_id=60868151492',
                specfoods: [{
                  checkout_mode: 1,
                  food_id: 900230327,
                  is_essential: false,
                  item_id: '455640115396',
                  name: '香辣鸡杂',
                  packing_fee: 0.5,
                  pinyin_name: 'xianglajiza',
                  price: 15,
                  promotion_stock: -1,
                  recent_popularity: 33,
                  recent_rating: 3.83,
                  restaurant_id: 'E2250635489379941286',
                  sku_id: '522195826884',
                  sold_out: false,
                  specs: [],
                  stock: 10000,
                  virtual_food_id: 848498469,
                  weight: 0
                }],
                specifications: [],
                tips: '6评价 月售33份',
                type: 0,
                virtual_food_id: 848498469
              }
            ],
            name: '商家推荐',
            window_type: 0
          }
        ],
        redpack: [],
        rst: {
          act_tag: 0,
          activities: [{
            attribute: '17.0',
            description: '新用户下单立减17元(不与其它活动同享)',
            icon_color: '70bc46',
            icon_name: '首单',
            id: 21538660347,
            is_exclusive_with_food_activity: true,
            name: '新用户立减(不与其他活动共享)',
            tips: '新用户下单立减17元(不与其它活动同享)',
            type: 103
          }],
          address: '武汉市东湖新技术开发区关山大道以东、凌华路以南融科天域第TC1号楼1层商21号、商22号',
          albums: [
            {
              count: 2,
              cover_image_hash: '2ab85bd6e74d82fc3a1546303044d9cfjpeg',
              name: '门面',
              photos: [
                {description: '', id: 40954154, image_hash: '2ab85bd6e74d82fc3a1546303044d9cfjpeg', type: 'FRONT'},
                {description: '', id: 40954178, image_hash: 'f21373dc08722f95bee895baf37e7c65jpeg', type: 'FRONT'}
              ]
            },
            {
              count: 1,
              cover_image_hash: 'cdef63d124d1e640f8b21bafaa937d55jpeg',
              name: '其他',
              photos: [{description: '', id: 40954266, image_hash: 'cdef63d124d1e640f8b21bafaa937d55jpeg', type: 'OTHER'}]
            },
            {
              count: 2,
              cover_image_hash: 'e8ea8abb5ed9867ac2af606fa88f1a28jpeg',
              name: '大堂',
              photos: [
                {description: '', id: 41080602, image_hash: 'e8ea8abb5ed9867ac2af606fa88f1a28jpeg', type: 'HALL'},
                {description: '', id: 41080618, image_hash: '170de21ed8fd029953e83c554f3d783ejpeg', type: 'HALL'}
              ]
            },
            {
              count: 3,
              cover_image_hash: 'b75687dea4d7ffeb03591ad3583c50aejpeg',
              name: '后厨',
              photos: [
                {description: '', id: 40954218, image_hash: 'b75687dea4d7ffeb03591ad3583c50aejpeg', type: 'KITCHEN'},
                {description: '', id: 40954242, image_hash: 'b7a97379083b988e0665a894b025b1e6jpeg', type: 'KITCHEN'},
                {description: '', id: 40954250, image_hash: '0523474cf709b0e3587c7b24cefb0725jpeg', type: 'KITCHEN'}
              ]
            }
          ],
          authentic_id: 3344760628092634,
          business_info: "{'lemon_support_tags': [{'color': 'cce23028', 'text': '首单减17', 'border': '4ce23028', 'background': null, 'type': 5, 'icon': null}], 'ad_info': null}",
          delivery_fee_discount: 0,
          delivery_mode: {
            border: 'FFFFFF',
            color: '',
            icon_hash: 'b9b45d2f6ff0dbeef3a78ef0e4e90abapng',
            id: 3,
            is_solid: true,
            text: '蜂鸟快送',
            text_color: 'FFFFFF'
          },
          description: '老乡鸡是以180天土鸡与农夫山泉炖制的肥西老母鸡汤为特色；食材甄选一线品牌供应商深度合作，品质放心；餐厅设计透明化厨房，将烹饪全程呈现在顾客面前。坚持健康营养的中式烹饪方式出品，深受消费者认可和欢迎。作为日常就餐更好的选择，老乡鸡已经服务消费者4.5亿人次，顾客排队成为餐厅日常。',
          distance: 3330,
          favored: false,
          flavors: [{id: 882, name: '其他快餐'}],
          float_delivery_fee: 5.1,
          float_minimum_order_amount: 10,
          has_story: true,
          id: 'E2250635489379941286',
          image_path: 'e9fa68c86f3dfd10768c56631faeeb06png',
          is_new: false,
          is_premium: true,
          is_star: true,
          is_stock_empty: 0,
          is_valid: 1,
          latitude: 30.482024,
          longitude: 114.413352,
          max_applied_quantity_per_order: 1,
          name: '老乡鸡(武汉光谷融科天域店)',
          next_business_time: '明天 06:30',
          only_use_poi: false,
          opening_hours: ['06:30/23:00'],
          order_lead_time: 43,
          out_of_range: false,
          phone: '027-87774627',
          piecewise_agent_fee: {
            description: '远距离配送费¥5.1',
            extra_fee: 1.6,
            is_extra: true,
            no_subsidy_fee: '',
            rules: [{fee: 5.1, price: 10}],
            tips: '远距离配送费¥5.1'
          },
          platform: 0,
          posters: [
            {
              id: 9795971,
              image_hash: 'df1f52f72d7ff7a2516675279a166b0apng',
              name: '点外卖 选老乡鸡！食材干净 放心卫生',
              type: 3,
              url: 'eleme://restaurant_promotion?restaurant_id=E2250635489379941286&banner_id=9795971'
            }
          ],
          promotion_info: '全国客服电话：4007661777↵若有订餐问题或店面电话不通畅，可拨打客服电话咨询。↵↵2003年，老乡鸡第1家快餐店肥西老母鸡在合肥开业；2012年，品牌升级为老乡鸡；2016年老乡鸡入驻南京、武汉；品牌创办至今，老乡鸡在全国已经有600多家直营店，并持续高速发展中。',
          qualification: {link: 'https://h5.ele.me/shop/certification/#/?restaurant_id=E2250635489379941286'},
          rating: 4.7,
          rating_count: 479,
          recent_order_num: 949,
          recommend: {color: '#e8470b', image_hash: 'ac124c767ffa7fd296d3e2d6f01798c6png', is_ad: false, reason: '口碑人气好店'},
          recommend_reasons: [{name: '回头客多'}],
          regular_customer_count: 0,
          scheme: 'https://h5.ele.me/shop/#id=E2250635489379941286',
          shop_sign: {brand_story: '', image_hash: '6b020c6b239007cabfbd2655b0148e7cpng'},
          status: 1,
          support_tags: [
            {border: 'dddddd', color: '666666', icon: '4e20966ca2a516de3f02fb9c7fd1bc6dpng', text: '其他快餐', type: 1},
            {border: '4c000000', color: '99000000', text: '支持自取', type: 20}
          ],
          supports: [{
            border: '90dddddd',
            description: '该商家支持开发票，请在下单时填写好发票抬头',
            icon_color: '999999',
            icon_name: '票',
            id: 4,
            name: '开发票',
            text_color: '666666',
            two_characters_icon_name: '发票'
          }],
          target_tag_path: 'd6a7283753e66cad4c4dc9a459d96a7fpng',
          theme: {
            default_color: '2395ff',
            header_style: 3,
            hongbao_style: 0,
            price_color: 'ff5339',
            third_tab_name: '商家',
            vanish_fields: []
          },
          type: 0,
          weight: {basic: 20000, maximum: 20000, unit: 20000, unit_fee: 20000}
        },
        user: {
          avatar: '',
          balance: 0,
          brand_member_new: 0,
          column_desc: {
            game_desc: '玩游戏领红包',
            game_image_hash: '05f108ca4e0c543488799f0c7c708cb1jpeg',
            game_is_show: 1,
            game_link: 'https://gamecenter.faas.ele.me',
            gift_mall_desc: '0元好物在这里'
          },
          current_address_id: 0,
          current_invoice_id: 0,
          delivery_card_expire_days: 0,
          email: '',
          gift_amount: 3,
          id: 5269108466,
          is_active: 1,
          is_email_valid: false,
          is_mobile_valid: true,
          mobile: '17754436915',
          point: 0,
          real_point: 0,
          supervip_status: 1,
          user_id: 5278812666,
          username: 'b202c1e2e43'
        }
      }
    }
  },
  created() {
    // this.$router.push({
    //   name:'goods',
    //   params:{
    //     id:13123
    //   }
    // })
    console.log(this.$route)
  },
  methods: {
    handleShopTabItem(index) {
      this.isShow = index
    }
  }
}
</script>

<style lang='less' scoped>
.shoptab{
  position: sticky;
  top: 0px;
  z-index: 2;
  display: flex;
  background: #fff;
  .shoptabItem{
    position: relative;
    flex: 1;
    text-align: center;
    font-size: .4rem;
    color: #666;
    border-bottom: 1px solid #ebebeb;
    line-height: 1.066667rem;
    text-decoration: none;
    span{
      display: inline-block;
      line-height: 1.066667rem;
      position: relative;
    }
  }
  .select{
    color: #333;
    font-weight: 700;
    span{
      &::after{
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        height: .053333rem;
        background-color: rgb(35, 149, 255);
      }
    }
  }
}
</style>
